### ISSUE TITLE
What is the limitation of Hexagon V75 that the Llama v2 7B Quantized model should be split into 8 Bin files ?

### ISSUE THREAD

**Issue by taeyeonlee** [quic/ai-hub-models#100]
Hello,
What is the limitation of Hexagon V75 that the Llama v2 7B Quantized model should be split into 8 Bin files ?

**Comment by gustavla** [comment]
Hi @taeyeonlee, thanks for your question. It has to do with the address space limitation of the Hexagon. We hope to abstract this away from the user in the future, but for now we have to manage these splits manually.
