### ISSUE TITLE
In QCS8550 development board, the inference of llama-v2-7b-chat using NPU failed."

### ISSUE THREAD

**Issue by holylong** [quic/ai-hub-models#105]
The model export process is roughly as follows:

`
python -m qai_hub_models.models.llama_v2_7b_chat_quantized.export --skip-downloading --skip-profiling --skip-inferencing

python qai_hub_models/models/llama_v2_7b_chat_quantized/demo.py --on-device --hub-model-id {model_id} --device "Samsung Galaxy S24 (Family)"

python gen_ondevice_llama.py --hub-model-id {model_id} --output-dir ./export --tokenizer-zip-path ./tokenizer.zip --target-gen snapdragon-gen2 --target-os android
`

All steps were successful.

The run prompted the following error:

Using libGenie.so version 1.0.0

[WARN]  "Unable to initialize logging in backend extensions."
[INFO]  "Using create From Binary"
[INFO]  "Allocated total size = 300255744 across 8 buffers"
[ERROR] "Could not create context from binary for context index = 0 : err 1009"
[ERROR] "Create From Binary FAILED!"
Failure to initialize model
ERROR at line 234: Failed to create the dialog.

**Comment by holylong** [comment]
run on android device
```
cd /data/local/tmp/shared_bins_snapdragon-gen2_android
export LD_LIBRARY_PATH=./
chmod a+x genie-t2t-run
./genie-t2t-run -c ./htp-model-config-llama2-7b.json -p "What is the most popular cookie in the world?" 
```

**Comment by bhushan23** [comment]
Hi @holylong 
You are generating assets for 8650 device (S24). In order to run on 8550, please provide (S23) as a target for export

**Comment by holylong** [comment]
> Hi @holylong You are generating assets for 8650 device (S24). In order to run on 8550, please provide (S23) as a target for export

Indeed, the Galaxy S24 is 8Gen3, and QCS8550 is 8Gen2. When executing export.py, there was no modification to S23. Thank you.
