### ISSUE TITLE
[Feature Request] New feature request

### ISSUE THREAD

**Issue by holylong** [quic/ai-hub-models#106]
Can the LLM model be converted locally? I have large machines and a QCS8550 development board on my premises. It seems the model still needs to be sent to the cloud for conversion? Constantly downloading and uploading is too slow; our company has a speed limit, and the internet speed is only 1M/s, which means one conversion takes two days.

**Comment by holylong** [comment]
The following steps are extremely slow to execute.
```
python -m qai_hub_models.models.llama_v2_7b_chat_quantized.export --skip-downloading --skip-profiling --skip-inferencing
python gen_ondevice_llama.py --hub-model-id {model_id} --output-dir ./export --tokenizer-zip-path ./tokenizer.zip --target-gen snapdragon-gen2 --target-os android
```

**Comment by kory** [comment]
It's definitely possible to convert locally given you have the QNN SDK installed--AI Hub just generates the correct SDK commands under the hood for you, so it's possible to go about it without the online service.

That said, the conversion path without AI Hub is not well documented. Please reach out to our team on [Slack](https://aihub.qualcomm.com/community/slack ) so we can assist further.
