### ISSUE TITLE
[BUG] File bug report I'm having a problem installing the gen_ondevice_llama operation on my phone deploying llama to run on the final phone

### ISSUE THREAD

**Issue by LLIKKE** [quic/ai-hub-models#107]
I refer to the `qai_hub_models/models/llama_v2_7b_chat_quantized/gen_ondevice_llama` tutorial using `qai-hub 0.15.0` to ensure that other versions are okay, and run it on a honor (gen3) phone`. /genie-t2t-run -c htp-model-config-llama2-7b.json -p “[INST] <<SYS>>\nYou are a helpful AI assistant.\n<<</SYS>>\n\nHave we been to Mars?[/INST]”` There's an error.

```
Using libGenie.so version 1.0.0

[WARN]  "Unable to initialize logging in backend extensions."
[ERROR] "Could not create context from binary for context index = 0 : err 5000"
[ERROR] "Create From Binary FAILED!"
Failure to initialize model
ERROR at line 244: Failed to create the dialog.
```

**Comment by mestrona-3** [comment]
@bhushan23 ^^

**Comment by LLIKKE** [comment]
I got help at `qualcomm-ai-hub.slack.com`, see `https://qualcomm-ai-hub.slack.com/archives/C06LGRS3AC8/p1729403552665709?thread_ts= 1729091620.195449&cid=C06LGRS3AC8`

**Comment by LLIKKE** [comment]
Hi, on LLaMA2_7B_Chat_Quantized, I noticed that the compile job on the ai hub is the QNN : v2.27.0.240926142112_100894 version, but no matter if I use 2.27.7 or 2.27.0 I get the same error!
HNBVL-AN00:/data/local/tmp $ cd llama2_7b_qnn/
user<|end_header_id|>\n\nWhat is France's capital?<|eot_id|><|start_header_id|>assistant<|end_header_id|>"            <
Using libGenie.so version 1.1.0

[WARN]  "Unable to initialize logging in backend extensions."
[INFO]  "Using create From Binary"
[INFO]  "Allocated total size = 300255744 across 8 buffers"
[ERROR] "Could not create context from binary for context index = 1 : err 4000"
[ERROR] "Create From Binary FAILED!"
[ERROR] "Failed to free device: 14003"
[ERROR] "Device Free failure"
Failure to initialize model
Failed to create the dialog.
I follow https://github.com/quic/ai-hub-apps/tree/main/tutorials/llm_on_genie. using 8gen3.
