### ISSUE TITLE
[BUG] File bug report : After logging in again, user is presented with login screen. 

### ISSUE THREAD

**Issue by quic-rneti** [quic/ai-hub-models#111]
1. In external dev trails, users tried to use AI hub. 
2. Once they login they are getting re-directed to the login page recursively. 
3. Instead user should be logged in and should be able to use AI hub API token. 
4. this is a a problem faced by external developer logins, not internal qualcomm logins. 

**Describe the bug**

**To Reproduce**
5. Click on '....'
6. Scroll down to '....'
7. See error

**Expected behavior**

**Stack trace**

**Host configuration:**
 - OS and version: [e.g. Linux, Windows, macOS]
 - QAI-Hub-Models version:
 - QAI-Hub client version:

**Additional context**

**Comment by mestrona-3** [comment]
Hi @quic-rneti , please feel free to ping me about this. We have wording on the first page suggesting first time users to get their API Token and implemented SSO re-direct last week to re-direct users to the page of interest after sign in. Please let me know if there is more context here I'm missing
