### ISSUE TITLE
Running models on Windows on Snapdragon

### ISSUE THREAD

**Issue by kristoftunner** [quic/ai-hub-models#12]
I would like to run the controlnet(https://github.com/quic/ai-hub-models/blob/main/qai_hub_models/models/controlnet_quantized/README.md) models on the HTP on snapdragon with windows. Is it possible to run the exported binary cache files of the controlnet models on snapdragon with windows?

In the docs I saw that the only support runtime is `qnn_lib_aarch64_android` for job compilation.

**Comment by bhushan23** [comment]
Hi @kristoftunner you can run exported context binary files on snapdragon with windows. Please make sure you are also using QNN SDK 2.19

We are in the actively validating these models on snapdragon on windows, it would be great if you can give it a spin and let us know how it goes :)

**Comment by kristoftunner** [comment]
@bhushan23  thx for the quick feedback, I will update you here once I have it running.

**Comment by kory** [comment]
Hi @kristoftunner , a clarification. You will need to use `--target_runtime qnn_bin` to get a cross platform asset.

**Comment by kristoftunner** [comment]
@bhushan23 the model binaries are working under windows, I tried it out on a volterra machine, thx
