### ISSUE TITLE
[Feature Request] New feature request

### ISSUE THREAD

**Issue by 1826133674** [quic/ai-hub-models#125]
**Is your feature request related to a problem? Please describe.**

I've purchased a Samsung S24 phone. How can I replicate the performance data of the large models you published on AIhub on my phone? For instance, baichuan2_7b_quantized. By the way, I've already downloaded their xxx.bin file.

**Comment by mestrona-3** [comment]
Hi @1826133674 , please check out our tutorial on how to do so, here under the `Run LLM on device` section https://github.com/quic/ai-hub-apps/tree/main/tutorials/llm_on_genie
