### ISSUE TITLE
[Feature Request] Add the use of https://pypi.org/project/torch-npu/ to enable the NPU of x1e-78-100

### ISSUE THREAD

**Issue by BrickDesignerNL** [quic/ai-hub-models#127]
**Is your feature request related to a problem? Please describe.**
Currently not all models in this repo utilize the NPU of the Qualcomm X Elite.
When the NPU can be use, it will improve performance and reduces the energy consumption.

**Describe the solution you'd like**
Add https://pypi.org/project/torch-npu/ dependency to all torch based projects (and make sure it's used by adding the import statement).

**Describe alternatives you've considered**
Running on CPU: takes long, kills battery life and eventually ventilator starts making noise.

**Comment by kory** [comment]
Torch-NPU is not supported on Qualcomm NPUs-- it targets Ascend AI Processors. Models must be compiled either using Qualcomm AI Hub,, or the Qualcomm AI Engine Direct SDK, and executed on device using the compiled asset.

**Comment by BrickDesignerNL** [comment]
Thank you @kory . I was not aware.
I'll try to understand/learn how to you those!
Thanks!
