### ISSUE TITLE
[BUG] Failure on building Llama_v2_7b_chat_quantized

### ISSUE THREAD

**Issue by sparkleholic** [quic/ai-hub-models#129]
I've tried many times to build HTP model for Llama_v2_7b_chat_quantized.
[llama_v2_7b_chat_quantized_TokenGenerato](https://app.aihub.qualcomm.com/jobs/jp8q82zop/)r steps succeeded,
However all [llama_v2_7b_chat_quantized_PromptProcessor](https://app.aihub.qualcomm.com/jobs/j57y62x95/) steps failed.
The doubt points is the following part.
This is a snippet of the compile log in ai-hub site.
```
[2024-11-22 10:15:14,396] [INFO] Running /qnn_sdk/bin/x86_64-linux-clang/qnn-context-binary-generator --backend /qnn_sdk/lib/x86_64-linux-clang/[libQnnHtp.so](https://libqnnhtp.so/) --model /tmp/93bb585a-841f-4661-abcb-06d4b24099fecbo5z4qa/[tmpwub1ws61.so](https://tmpwub1ws61.so/) --output_dir /tmp/93bb585a-841f-4661-abcb-06d4b24099fecbo5z4qa/tmp4azwf6jc --binary_file qnn_model --config_file /tmp/93bb585a-841f-4661-abcb-06d4b24099fecbo5z4qa/tmp4azwf6jc/htp_context.json

[2024-11-22 10:21:55,069] [INFO] qnn-context-binary-generator pid:499
0.0ms [ ERROR ] **fa_alloc.cc:3866:ERROR:graph requires estimated allocation of 2347229 KB, limit is 2097152 KB**
0.0ms [ ERROR ] graph_prepare.cc:742:ERROR:error during serialize: memory usage too large
0.0ms [ ERROR ] graph_prepare.cc:6095:ERROR:Serialize error: memory usage too large
0.0ms [ ERROR ] QnnDsp <E> Graph prompt_part4 serialization failed
0.0ms [ ERROR ] QnnDsp <E> Failed to serialize graph prompt_part4
0.0ms [ ERROR ] QnnDsp <E> Context binary serialization failed
0.0ms [ ERROR ] QnnDsp <E> Get context blob failed.
0.0ms [ ERROR ] QnnDsp <E> Failed to get serialized binary
0.0ms [ ERROR ] QnnDsp <E> Failed to get context binary with err 0x138f
399119.1ms [ ERROR ] Could not get binary.
Graph Finalize failure
[2024-11-22 10:21:55,239] [ERROR] Conversion to context binary failed with exit code 15
```

**In my local machine, there is proper memory to run and no limitations like described in the above log.
I wonder if this failure come from the ai-hub cloud resource or not.**

**To Reproduce**
```
$ python3 -m qai_hub_models.models.llama_v2_7b_chat_quantized.export --device "QCS8550 (Proxy)" --skip-inferencing --skip-profiling --skip-downloading --output-dir genie_bundle
```
**Expected behavior**
Success

**Stack trace**

**Host configuration:**
 - OS and version: Linux
 - QAI-Hub-Models version:  Llama_v2_7b_chat_quantized
 - QAI-Hub client version: qai_hub_models (installed 2024.11.22)

**Comment by mestrona-3** [comment]
Hi @sparkleholic, thanks for the issue! We have a few inquiries about llama_v2 on the QCS8550 device. We're working on a fix and will share as soon as it's available. I'd encourage you to join our [Slack Community](https://aihub.qualcomm.com/community/slack) to hear when it has been released!

**Comment by sparkleholic** [comment]
@mestrona-3 
Thanks for the response. On slack, I left a message. 
Could you please confirm whether the above error is a problem with my local PC or an ai-hub cloud resource issue? In the case of my local PC, there is much more room than the resource constraints in the error message.

**Comment by sparkleholic** [comment]
In slack, Qcom announced today about this.
```
Bug Fixes and Improvements
 ...
Llama2 support dropped for QCS8550 (Proxy) due to out-of-memory issue
```

It means the issue is a problem of ai-hub cloud resource.
I wonder when this issue will be resolved and it will be available again.

**Comment by mestrona-3** [comment]
Hi @sparkleholic , we're actively looking into this and are hoping to resolve it as soon as possible. This will be shared in slack  when applicable.
