### ISSUE TITLE
Execute Dockerized TFLite model with QCS6490

### ISSUE THREAD

**Issue by rjtokenring** [quic/ai-hub-models#133]
**Describe the issue**
Hi, I'm trying to execute yolo with a Docker container on QCS6490. Docker is executed on QCS6490 with Qualcomm linux v1.1.
QNN SDK 2.27

After installing required QNN libraries and exporting devices, I'm following instructions described here.

https://github.com/quic/ai-hub-models/issues/26

To build and run container, I've started from this guide: https://docs.qualcomm.com/bundle/publicresource/topics/80-70015-50/image-segmentation-using-python.html?vproduct=1601111740013072&versionId=35c3bc73-6ae0-4179-b66b-a01844b5a87f&facet=Qualcomm%20Intelligent%20Multimedia%20SDK

After executing code mentioned in above issue (issue/26), I get this error:
```
[INFO] LD_LIBRARY_PATH = /root/qairt/2.27.0.240926/lib/aarch64-ubuntu-gcc9.4
[INFO] LD_LIBRARY_PATH exists = True
[INFO] ADSP_LIBRARY_PATH = /root/qairt/2.27.0.240926/lib/hexagon-v68
[INFO] ADSP_LIBRARY_PATH exists = True
[INFO] Skel dir path = /root/qairt/2.27.0.240926/lib/hexagon-v68/unsigned
[INFO] Path exists = True
QNNTFLiteDelagate loaded
/prj/qct/webtech_hyd18/mlg_user_admin/qaisw_source_repo/qaisw_repo_release/snpe_src/avante-tools/prebuilt/dsp/hexagon-sdk-4.2.0/ipc/fastrpc/rpcmem/src/rpcmem_android.c:38:dummy call to rpcmem_init, rpcmem APIs will be used from libxdsprpc
ERROR: [QNN Delegate] Failed to create device_handle for Backend ID 6, error=1008
Traceback (most recent call last):
  File "/root/tflite_qnn.py", line 36, in <module>
    interpreter = tf.lite.Interpreter(
  File "/root/py/.venv/lib/python3.10/site-packages/tensorflow/lite/python/interpreter.py", line 495, in __init__
    self._interpreter.ModifyGraphWithDelegate(
RuntimeError: Restored original execution plan after delegate application failure.
```

**Expected behavior**
Clear guide on how to execute model with QNN Delegate supported as containerized application to be executed on Qualcomm linux. 

**Host configuration:**
 - OS and version: Qualcomm linux 1.1
 - QAI-Hub-Models version:
 - QAI-Hub client version:

**Comment by mestrona-3** [comment]
Closing this issue as we discussed on Slack that Discord may be a good place to discuss

**Comment by tmqcaiml** [comment]
@rjtokenring  Hi can you also share the solution here, would be great as I am also getting the same error.

**Comment by philippe-heitzmann** [comment]
@rjtokenring @mestrona-3 Would appreciate any update on this - also having the same error.

**Comment by mestrona-3** [comment]
Hi all - closed issues are not monitored. Please ask any new questions by filing a new Github Issue or on [Slack](http://aihub.qualcomm.com/community/slack). This specific question related to lower level on-device details is outside our teams area of expertise and we have previously recommended [Qualcomm Developers Discord ](https://discord.gg/TzvP3JhfzX). Thanks.
