### ISSUE TITLE
[BUG] Segmentation model accuracy issues with QCS6490 - INT8 - TFLite

### ISSUE THREAD

**Issue by quic-rneti** [quic/ai-hub-models#134]
**Describe the bug**

Segmentation model accuracy is not good - customers picked TFLite INT8 model from AI hub, and used it with GST pipeline. 
It is not giving good results. This feedback was given by two different customers. 
This model is also tagged as IMSDK compatible. 

**To Reproduce**

self explanatory 

**Expected behavior**

<img width="766" alt="image" src="https://github.com/user-attachments/assets/d84c326e-54a9-4440-93b2-87f3c7c65c36">

**Stack trace**

**Host configuration:**
 - OS and version: [e.g. Linux, Windows, macOS]
 - QAI-Hub-Models version:
 - QAI-Hub client version:

**Additional context**

**Comment by mestrona-3** [comment]
Hi @quic-rneti, which segmentation model was used so that we can reproduce the issue?

**Comment by quic-rneti** [comment]
Details are available in above screenshot, but sharing again : 
Models used from AI hub – DeeplabV3_Quantized
Devices tried – QCS6490 – RB3 Gen2 – LE build, not Android proxy device. 
Dataset – There is no specific dataset – customers just tried with their deployment scenario.
