### ISSUE TITLE
[BUG] not found sam git repo

### ISSUE THREAD

**Issue by bbtty0423** [quic/ai-hub-models#135]
repository 'https://github.com/dmckinnon/segment-anything/' not found

**Comment by mestrona-3** [comment]
Hi @bbtty0423, where do you see the link you pasted above? We have https://github.com/quic/ai-hub-models/tree/main/qai_hub_models/models/sam which is what is linked on our Segment Anything model?

**Comment by mestrona-3** [comment]
Hi @bbtty0423, thanks for reporting this! We dug into it a bit more and will have a fix out next release (next week) for it.
