### ISSUE TITLE
[Question] How to build a model offline

### ISSUE THREAD

**Issue by sparkleholic** [quic/ai-hub-models#139]
As far as I know, when I try to build a model via export feature, it builds on my local pc, and during the build process, it uploads files and downloads, so I guess the build steps requires Qcom-Ai-Hub cloud features.

I'm curious if it is possible to build a model without Qcom-Ai-Hub cloud.

**Comment by kory** [comment]
We don't support a local-only build process at this time, and we have no plans to support offline compilation.
