### ISSUE TITLE
The whole android folder and the apks are missing from the repository 

### ISSUE THREAD

**Issue by Zbrooklyn** [quic/ai-hub-models#2]
The whole android folder and the apks are missing from the repository

**Comment by quic-rneti** [comment]
This was not added due to git LFS problem. Added these on January 21, 22, 2024

**Comment by MarkYav** [comment]
@quic-rneti  Where the Android examples (projects) could be found?

**Comment by kory** [comment]
G

**Comment by kory** [comment]
Hi Mark,

Thanks for the feedback here. We have these apps internally, but just haven't pushed them out yet. We're working on some last touches, so expect them next week.

At the moment, we have apps for Image Segmentation and Super Resolution.

**Comment by Benoitwill** [comment]
Hello,

Are there any updates regarding the implementation of TFLite models for Android?

**Comment by Bear8006** [comment]
there is no qtld-release.aar  when trying to build android app for image classification or super resolution

**Comment by mestrona-3** [comment]
Hi @Benoitwill , @Bear8006! We are working on the final touches and will share an announcement on slack once this is available. Stay tuned!

**Comment by kory** [comment]
These are now released.

**Comment by MarkYav** [comment]
> These are now released.

@kory Thank you for your work! Where the Android examples (projects) could be found? Could you please attach a link?

Once again thank you for your work!
