### ISSUE TITLE
apps/android  Building Android APP failed

### ISSUE THREAD

**Issue by ZhangWeiOneTwo** [quic/ai-hub-models#30]
import com.qualcomm.qti.QnnDelegate  file is not found

**Comment by mestrona-3** [comment]
Hey @ZhangWeiOneTwo, seems like you're missing the QNN delegate SDK.

You can download the latest SDK with the .aar [here](https://tetra-public-assets.s3.us-west-2.amazonaws.com/qai-hub-apps/qnn/linux/2.20.1.240223.zip). No credentials needed. An update to the repo to reflect that is a work in progress.

**Comment by ZhangWeiOneTwo** [comment]
@mestrona-3 thanks.
Can you re-improve the Android project, because I imported this library and still reported an error, and I did not find the QnnDelegate file. Thank you very much.

**Comment by kory** [comment]
Can you try this link instead?
https://qaihub-public-assets.s3.us-west-2.amazonaws.com/qai-hub-apps/qnn/linux/2.20.0.240223.zip

Kory

**Comment by ZhangWeiOneTwo** [comment]
@kory Hello! Can you show me the QnnDelegate class?

**Comment by ZhangWeiOneTwo** [comment]
I successfully compiled the Android demo, thanks。
Thanks to everyone in the Qualcomm AI Hub channel。

**Comment by tumuyan** [comment]
> Can you try this link instead? We realized the previous link was missing assets. https://qaihub-public-assets.s3.us-west-2.amazonaws.com/qai-hub-apps/qnn/linux/2.20.0.240223.zip

I have the same problem, but I couldn't download the assets 

![image](https://github.com/quic/ai-hub-models/assets/3126801/74e1879c-530e-4654-b19a-5936c43be24d)

**Comment by ZhangWeiOneTwo** [comment]
@tumuyan 你可以问Qnn资源新的下载地址，这个地址可能是过期了。直接新开一个问题，这里问题已经关闭了。他们应该是不会回复了，我有资源但是太大了，也没法给你。
