### ISSUE TITLE
[BUG] Improvements for apps/Android/ImageClassification/build_apk.py

### ISSUE THREAD

**Issue by fangxingSR** [quic/ai-hub-models#38]
**Describe the bug**
[](https://github.com/quic/ai-hub-models/blob/main/apps/android/ImageClassification/build_apk.py)
There is an issue with build_apk.py: when only the qnnsdk and model_path are input, the model selection menu should not be printed using printmenu(), because the model will invariably be assigned the value of 'classification.tflite'.

I have modified the decision rule: the model selection menu will only be printed if neither model_name nor model_path has been provided.
It is suggested that line 45 be changed to: 
                                                                       if not args.model_name and not args.model_path:

**Comment by mestrona-3** [comment]
Hi @fangxingSR, thanks for reporting this issue. We'll look into this and provide an update here.

**Comment by fangxingSR** [comment]
I created and submitted a branch to   https://github.com/quic/ai-hub-models/pull/41   . This submission aims to optimize the logic of the build_apk.py script and update the README.md file. I hope this contribution will bring positive benefits to the community and look forward to it being helpful to everyone.
