### ISSUE TITLE
Llama7B repo empty currently

### ISSUE THREAD

**Issue by grundman** [quic/ai-hub-models#4]
The LLama 7B repo is currently empty, I can't find the conversion scripts or find converted .so files on the hugging face page. Is there an ETA for those to be uploaded?

https://github.com/quic/ai-hub-models/tree/main/qai_hub_models/models/llama_v2_7b_chat_quantized

**Comment by srikris-sridhar** [comment]
We cannot distribute the 4-bit quantized model so we are working on making it such that you can create this yourself. Stay tuned!

**Comment by YixinSong-e** [comment]
> We cannot distribute the 4-bit quantized model so we are working on making it such that you can create this yourself. Stay tuned!

Is there any update?

**Comment by Junhyuk** [comment]
can you please update the way how to convert to qnn model from llama 7B ?

**Comment by mestrona-3** [comment]
Hi All, we are happy to see all the interest around Llama 7B. We are actively working on this and will share an update via Qualcomm AI Hub Community Slack when it is ready, we're working to get this out as soon as possible!

**Comment by bhushan23** [comment]
Hi @grundman @r-wheeler @YixinSong-e  @Junhyuk 

Llama2 export scripts are out now https://github.com/quic/ai-hub-models/tree/main/qai_hub_models/models/llama_v2_7b_chat_quantized

Please give it a try and let us know how it goes

**Comment by ao-zz** [comment]
@bhushan23
Will the `.so` or `.bin` files be uploaded on the hugging face page ? Since I do not have a device with 40+ GB RAM to meet the demand of export script.

**Comment by bhushan23** [comment]
We do emit instructions to increase swap space to help you export these models if memory is low.

We cannot share exported models as we cannot distribute weights. But, our goal is to make it easy for users to be able to export this.
