### ISSUE TITLE
Label.txt file for yolov8_det.tflite model

### ISSUE THREAD

**Issue by MuhammadShifa** [quic/ai-hub-models#43]
I need the label.txt file for yolov8_det,tflite model. I am trying to acheive it throught ultralytics official package but it show the error of metadata file. Please provide the names of classes on which the model is trained.

**Comment by mestrona-3** [comment]
Hi @MuhammadShifa, we don't have labels.txt but these are the class names, offset by 1.
https://gist.github.com/AruniRC/7b3dadd004da04c80198557db5da4bda

There's also more information on the model used [here](https://huggingface.co/qualcomm/YOLOv8-Detection)
