### ISSUE TITLE
Incorrect Comment

### ISSUE THREAD

**Issue by BHilldore** [quic/ai-hub-models#47]
https://github.com/quic/ai-hub-models/blob/4c5f86530b1b6d8f74967f60734b01f8709dbe35/apps/android/ImageSuperResolution/superresolution/src/main/java/com/qcom/imagesuperres/Utils.java#L16

Comment states that image is normalized from [-1, 1] rather than [0, 1].

**Comment by mestrona-3** [comment]
Thank you for submitting this! We'll get it fixed up.

**Comment by gustavla** [comment]
The SuperResolution app has been re-launched as part of a new AI Hub Apps repository:

* https://github.com/quic/ai-hub-apps/tree/main/apps/android/SuperResolution

This issue has been resolved there. Thanks again for reporting it!
