### ISSUE TITLE
pacakage error

### ISSUE THREAD

**Issue by Vinaysukhesh98** [quic/ai-hub-models#48]
ai-hub-models/apps/android/ImageSuperResolution/superresolution/src/main/java/com/qcom/imagesuperres/SuperResolution.java:17: error: package com.qualcomm.qti does not exist
import com.qualcomm.qti.QnnDelegate;

**Comment by Vinaysukhesh98** [comment]
python build_apk.py  -q  $QNN_SDK_ROOT while running im getting below error

build/esrgan/esrgan.tflite
MODEL IS ESRAGAN
Traceback (most recent call last):
  File "build_apk.py", line 138, in <module>
    shutil.copy(aarfile, destaar)
  File "/home/mbuhyd/anaconda3/envs/ai-hub/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mbuhyd/anaconda3/envs/ai-hub/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/qcom/aistack/qnn/2.19.2.240210/lib/android/qtld-release.aar'

**Comment by gustavla** [comment]
Hi @Vinaysukhesh98, sorry you are having this issue. Could you describe how you downloaded and prepared the QNN SDK, and how you set QNN_SDK_ROOT? Thanks.

**Comment by mestrona-3** [comment]
Hi @Vinaysukhesh98, we've re-released the apps in a new location. Please try out the latest version of Super Resolution! AI https://github.com/quic/ai-hub-apps/tree/main/apps/android/SuperResolution

**Comment by Vinaysukhesh98** [comment]
HI @mestrona-3 @gustavla , thanks for your update.
