### ISSUE TITLE
Windows on ARM support

### ISSUE THREAD

**Issue by khmyznikov** [quic/ai-hub-models#5]
Is this samples can be executed on Volterra?

**Comment by srikris-sridhar** [comment]
We are actively working on Windows on Arm support. This is pretty important to us. Stay tuned.

**Comment by kory** [comment]
Hello,

Exported ONNX models work on ARM windows with the [onnxruntime-qnn](https://pypi.org/project/onnxruntime-qnn/) package.

The python package itself can run on Windows for ARM, but only via x86 emulation. This is because some of our dependencies (eg. h5py) do not yet have Windows ARM builds.
