### ISSUE TITLE
import com.qualcomm2.QnnDelegate fail

### ISSUE THREAD

**Issue by tumuyan** [quic/ai-hub-models#50]
import com.qualcomm2.QnnDelegate fail in building apps/android, 

In #30 the solution is download qnn sdk, but it is hard to find the qnn sdk and the assets link access denied.

So how to find the latest qnn sdk? I use windows and android studio,  also I have install qualcomm_ai_engine_direct.2.22.6.240515.Windows-AnyCPU.exe and qualcomm_neural_processing_sdk.2.22.6.240515.Windows-AnyCPU.exe

**Comment by kory** [comment]
Hi tumuyan,

You can find the latest SDK here: https://softwarecenter.qualcomm.com/api/download/software/qualcomm_neural_processing_sdk/v2.22.6.240515.zip
