### ISSUE TITLE
Using NPU in ImageClassification demo app

### ISSUE THREAD

**Issue by ciaranbor** [quic/ai-hub-models#51]
I am attempting to use the [image classification Android app](https://github.com/quic/ai-hub-models/tree/main/apps/android/ImageClassification) to verify NPU usage with the tflite runtime. I am using a phone with the Snapdragon 8 Gen 3 chipset.

When running the app, the execution time for CPU and NPU (after a few executions of each) settle at around the same, ~14ms compared to the reported NPU execution time of <1ms. Is there any way to debug this or verify whether the tflite runtime is using the NPU?

I have tried both downloading the MobileNet-v3-Small model from [aihub](https://aihub.qualcomm.com/mobile/models/mobilenet_v3_small) and using the [this export script](https://github.com/quic/ai-hub-models/blob/main/qai_hub_models/models/mobilenet_v3_small/export.py). I have also tried installing the app with the provided `build_apk.py` script and using Android Studio, after manually copying the tflite model to `assets`. In each case the result is the same.

When I try the app on a phone without an NPU, it crashes while trying to register the HTP backend. This leads me to believe the HTP backend is being registered correctly for the Gen 3 phone.

**Comment by mestrona-3** [comment]
Hi @ciaranbor, thank you for reporting this! This is a known issue, that the app performance doesn't reproduce the expected latency in AI Hub. we're actively working on a fix and are hoping to have an update by our next release.

**Comment by MrRace** [comment]
mark~

**Comment by kory** [comment]
This application was replaced by https://github.com/quic/ai-hub-apps/tree/main/apps/android/ImageClassification.

Extra care was taken in this app to replicate the performance AI Hub reports. Let us know (open an issue on the quic/ai-hub-apps repository) if you are unable to reproduce AI Hub performance with the new app.
