### ISSUE TITLE
[Feature Request] OpenPose model has no option to use .bin file as target runtime.

### ISSUE THREAD

**Issue by ukc-work** [quic/ai-hub-models#56]
With target-runtime option as qnn, it uses .so file only. How can I use .bin file for the same model ?

**Comment by kory** [comment]
Unfortunately, at the moment, our export scripts support context binary only for non-Android devices.
If you choose a Windows device (Snapdragon X Elite CRD), we compile to a qnn .bin.

All of our models can be compiled to `.bin` via AI Hub, but you would need to make a code change & install the package from source.
