### ISSUE TITLE
Incorrect formats

### ISSUE THREAD

**Issue by dc-dc-dc** [quic/ai-hub-models#6]
I believe that this repo is the source for the models under the [Qualcomm huggingface account](https://huggingface.co/qualcomm)? If not feel free to close this issue as it does not pertain

I was going through some models and noticed that although the file extension is `.tflite` some files are actually of the ELF format

```bash
❯ head -c 20 ResNet50.tflite
ELF�%                
```

Repos that are fine:
- VIT

Repos where i noticed the `tflite` files are actually ELF:
- ResNet50
- ResNext
- Real-ESRGAN-x4plus
- FFNet-40S

**Comment by srikris-sridhar** [comment]
Good catch! Thanks for filing the issue. I believe we are working on this and should fix this shortly.

**Comment by shreyajn** [comment]
Thanks for reporting the issue! It should be fixed now.😄
