### ISSUE TITLE
[Feature Request]  Change the super resolution algorithm solution

### ISSUE THREAD

**Issue by vongocminh778** [quic/ai-hub-models#63]
**Describe the solution you'd like**
Can I adjust the resolution of the super resolution algorithms to 640x480 instead of 128x128?

**Comment by mestrona-3** [comment]
Hi @vongocminh778, you can do this yourself by passing the following flag 
python -m qai_hub_models.models.<sr_model>.export ... ---height <blah> --width <blah>
