### ISSUE TITLE
Failure Reason Must use --truncate_64bit_io when input tensors have type int64.

### ISSUE THREAD

**Issue by AndreaChiChengdu** [quic/ai-hub-models#68]
macos 15 with m3 soc
as title, after i submit my compile task(cli model. qai-hub submit-compile-job) model with int64 input.  
build fail and responce that must use"--truncate_64bit_io", my question is where and how to enable this parameter --truncate_64bit_io ？
thanks～

**Comment by noahzhy** [comment]
same problem, did you fixed?

**Comment by mestrona-3** [comment]
Hi @noahzhy, we encourage you to reach out to our AI Hub team and community for faster response via [Slack](http://aihub.qualcomm.com/community/slack). Closed issues make it very difficult to track questions.
