### ISSUE TITLE
سکس

### ISSUE THREAD

**Issue by Alijmali1352** [quic/ai-hub-models#70]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Stack trace**

**Host configuration:**
 - OS and version: [e.g. Linux, Windows, macOS]
 - QAI-Hub-Models version:
 - QAI-Hub client version:

**Additional context**

**Comment by mestrona-3** [comment]
Please provide a question in your GitHub issue. Closing as this is the issue template.
