### ISSUE TITLE
[BUG] SemanticSegmentation File missing, unable to execute

### ISSUE THREAD

**Issue by ZhangY427** [quic/ai-hub-models#74]
apps/android/SemanticSegmentation

The downloaded code is not recognized as a code package in Android.
Compared with the previous ImageClassification file, it is found that build.gradle, settings.gradle and other files are missing
<img width="244" alt="微信图片_20240723140456" src="https://github.com/user-attachments/assets/38e007f3-7f21-4de6-bb0d-b80192e32271">

**Comment by sunoking** [comment]
I encountered the same problem，Perhaps only Qualcomm authors can solve: upload complete code.

**Comment by mestrona-3** [comment]
Closing this issue as we've re-published the apps. @ZhangY427 please use the link above and let us know if you have issues! We also encourage you to join our external[ slack channel ](https://aihub.qualcomm.com/community/slack)if you haven't already.
