### ISSUE TITLE
NO of Inference Set to 20 or 30

### ISSUE THREAD

**Issue by Vinaysukhesh98** [quic/ai-hub-models#75]
**Is your feature request related to a problem? Please describe.**
Instead of running single inference can we run multiple inference in Super Resolution so we can analyse the model behaviour.

**Describe the solution you'd like**
if we add that feature we can increase the execution time that helps easy for analysis , currently it was performing single inference i think.

Note: currently we are performing upscale of 4 instead of this can we try Upscale of 16 any how now every once is looking for 4k, genration.

**Comment by shreyajn** [comment]
We have deliberately kept the sample apps easy and simple so people can understand the basic follow and edit as they need for their apps. If you want the sample app to do multiple inferences, we recommend cloning the repo and editing the code / experimenting with it. 

You can experiment with the model on AI Hub to see if 16x upscale is supported or not. If you like the performance and quality of the output then you can use that network with the app above.

**Comment by mestrona-3** [comment]
Closing this issue. @Vinaysukhesh98, please let us know if you have any further questions via Slack or a new Github issue.
