### ISSUE TITLE
 Genie C API : Sample android app

### ISSUE THREAD

**Issue by taeyeonlee** [quic/ai-hub-models#79]
Qualcomm released the new version (2.25.0.240728) of qualcomm_ai_engine_direct(A.K.A QNN).
There is Qualcomm Genie SDK which includes Genie C API.
Could you please share a sample app using Genie C API ?

**Comment by mestrona-3** [comment]
Thank you for the feature request. We have received this feature request across many channels, so we will close this issue. We are actively working on this and will share it as soon as we can.
