### ISSUE TITLE
Create ControlNet catalog

### ISSUE THREAD

**Issue by MarkYav** [quic/ai-hub-models#8]
### Context
We want to run the [ControlNet](https://aihub.qualcomm.com/models/controlnet_quantized) model on Android devices.

### Problem
It is not clear what condition was used for [ControlNet](https://aihub.qualcomm.com/models/controlnet_quantized). It would be very kind of you if you could specify what type of condition was used (Canny Edge, M-LSD Lines, Scribbles, etc.)

### Proposed Solution
Make a catalog of quantized ControlNet models for each type of condition with the corresponding description.

**Comment by bhushan23** [comment]
Thanks @MarkYav for reporting this. this model used Canny Edge condition. 
We will update this into our documentation and description to make it clear.

**Comment by MarkYav** [comment]
@bhushan23 Thank you for your prompt reply! Can we expect to have several ControlNet models with different conditions available? Or how can I make it in AI Hub?

**Comment by bhushan23** [comment]
Hi @MarkYav I missed your message.

We do have plans to release receipts and ControlNet with different conditions available in coming months.
We do welcome community contributions and would like to see that going.

Meanwhile we can follow BYOM (Bring Your Own Model) path
    - You can follow these instructions to submit your Torch model on Hub https://app.aihub.qualcomm.com/docs/hub/profile_examples.html#profiling-a-pytorch-model
    - We will soon put out a recipe out for LLaMA, ControlNet that you can follow to create equivalent ControlNet of your variants with different conditions

We will update here once ControlNet/LLaMa receipt is out. We will be happy to accept your contributions on variations on controlNet once that is in place.

**Comment by mestrona-3** [comment]
Closing this issue as we've added the Conditioning Input (Canny-Edge) to ControlNet in our latest release of Model Zoo. I've added different variations of ControlNet to our list of requested models, though @MarkYav please feel free to try them out on AI Hub before that.
