### ISSUE TITLE
[Question] Where did your tflite model come from？

### ISSUE THREAD

**Issue by Ss-shuang123** [quic/ai-hub-models#86]
Your example code is all pytorch related. Is your tflite model reconstructed or converted?
Can you provide more detailed information? Because it seems that QNN is more friendly to tiflite support.
Very important！！！Thanks a lot!

**Comment by gustavla** [comment]
Hi @Ss-shuang123,

We go from PyTorch to TFLite using AI Hub compile jobs. You can read more about them here: https://app.aihub.qualcomm.com/docs/hub/compile_examples.html#compiling-pytorch-to-tflite
