### ISSUE TITLE
[BUG] The generated text is strange from 8 QNN Context Bins which are generated in AI Hub.

### ISSUE THREAD

**Issue by taeyeonlee** [quic/ai-hub-models#87]
Dear Qualcomm,

According to the Sample App ((QNN API C++ : https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-50/sample_app.html),
I made an Android app using Android NDK C++ and pytorch to run the 8 QNN Context Bins on HTP Backend in Android mobile S24/23 Ultra.
The text is generated as like below. The generated text is strange.
Could you please let me know what the problem is ?

Prompt : "Could you tell me about Llama LLM Model ?"
Generated Text : "Of course, no, the possibilities or quElse. providing 3 of a shelter, perhaps? no. Noal 2 verz (fileadas (after) for theCalculematic!Vos itif and that time,icing at the Sh internal one of the 8 image not alwaysCommanager notes this. to. or on time, perhaps the Or. (In US dollars Bill – because at'23 will, which book"
(Max num of token is 90)

llama_v2_7b_chat_quantized_PromptProcessor_1_Quantized.bin
llama_v2_7b_chat_quantized_PromptProcessor_2_Quantized.bin
llama_v2_7b_chat_quantized_PromptProcessor_3_Quantized.bin
llama_v2_7b_chat_quantized_PromptProcessor_4_Quantized.bin
llama_v2_7b_chat_quantized_TokenGenerator_1_Quantized.bin
llama_v2_7b_chat_quantized_TokenGenerator_2_Quantized.bin
llama_v2_7b_chat_quantized_TokenGenerator_3_Quantized.bin
llama_v2_7b_chat_quantized_TokenGenerator_4_Quantized.bin

In ubuntu PC, taeyeon@Desktop-PC:~/QCT_AI_Hub$ python -m qai_hub_models.models.llama_v2_7b_chat_quantized.demo
       generated Text : 					
                      Prompt: "Could you tell me about Llama LLM Model ?"
                      Response: "Of course! Llama LLM (LLM) is a powerful language model developed by Meta AI that is capable of generating coherent and natural-sounding text. It is a variant of the LLaMA model (LLaMA: Open and Efficient Foundation Language Models, Touvron et al. 2023) and is specifically designed for tasks that require a more nuanced and expressive language"
(Max num of token is 90)

Has Qualcomm ever run the 8 QNN Context Bins which are generated from Ai Hub, to generate the Text ?
What text are generated for the prompt "Could you tell me about Llama LLM Model ? "  ?

I compared the inputs (input_ids, attention_mask, position_ids_cos, position_ids_sin, past_values) for the PromptProcessor_1/2/3/4 and TokenGenerator_1/2/3/4 between my C++ code and Python, using the same prompt.
The inputs (attention_mask, position_ids_cos, position_ids_sin) for the PromptProcessor_1/2/3/4 and TokenGenerator_1/2/3/4 in my C++ code are same as in python, using the same prompt, until 9 generaed tokens.
The input_ids and ​past_values which are generated from Bins are different between my C++ code and Python.

Best regards,

**Comment by bhushan23** [comment]
Hi @taeyeonlee 
Could you please verify if you are handling intermediate inputs correctly?
Seems like token generation is getting results off from AI Hub vs local app that you have built.

Please ensure past key values are corrected before each run as shown in https://github.com/quic/ai-hub-models/blob/main/qai_hub_models/models/_shared/llama/app.py?

Could you share how you are connecting these models together?

**Comment by taeyeonlee** [comment]
Hi @bhushan23 

According to the python code (https://github.com/quic/ai-hub-models/blob/main/qai_hub_models/models/_shared/llama/),  I coded the c++ code in Android App using NDK and pytorch libs.

For example, after running llama_v2_7b_chat_quantized_TokenGenerator_2_Quantized.bin,  there're 513 outputs from the llama_v2_7b_chat_quantized_TokenGenerator_2_Quantized.bin.
the last output (ie. output[512]) has the tensor shape [1, 1, 4096], and it's data type is QNN_DATATYPE_UFIXED_POINT_16.
and the other outputs (output[0~511]) has the tensor shape [1, 1, 128, 1] or [1, 1, 1, 128], and it's data type is QNN_DATATYPE_UFIXED_POINT_8.

to run the next bin (llama_v2_7b_chat_quantized_TokenGenerator_3_Quantized.bin), prepare the inputs for llama_v2_7b_chat_quantized_TokenGenerator_3_Quantized.bin.
There're 516 inputs for llama_v2_7b_chat_quantized_TokenGenerator_3_Quantized.bin.
The first input (ie. input[0], called as input_ids) has the tensor shape [1, 1, 4096], and it's data type is QNN_DATATYPE_UFIXED_POINT_16.
The second input (ie. input[1], called as attention_mask) has the tensor shape [1, 1, 1, 1024], and it's data type is QNN_DATATYPE_UFIXED_POINT_16.
The third input (ie. input[2], called as position_ids_cos) has the tensor shape [1, 1, 1, 64], and it's data type is QNN_DATATYPE_UFIXED_POINT_16.
The forth input (ie. input[3], called as position_ids_sin) has the tensor shape [1, 1, 1, 64], and it's data type is QNN_DATATYPE_UFIXED_POINT_16.
and the other inputs (input[4~515]) has the tensor shape [1, 1, 128, 1023] or [1, 1, 1023, 128], and it's data type is QNN_DATATYPE_UFIXED_POINT_8.

For the first input (ie. input[0], called as input_ids), the output (ie. output[512]) of the previous bin (llama_v2_7b_chat_quantized_TokenGenerator_2_Quantized.bin) is converted to float, using the function (m_ioTensor.convertToFloat), which was implemented by Qualcomm. (using the offset=-24661  scale=0.016098 which are provided bin file).
and the float is converted to QNN_DATATYPE_UFIXED_POINT_16, using the the function (m_ioTensor.copyFromFloatToNative), which was implemented by Qualcomm. (using the offset=-24661  scale=0.016098 which are provided bin file).

For the second, third, forth input (input[1~3]), the same values are used for the current bin (llama_v2_7b_chat_quantized_TokenGenerator_3_Quantized.bin) and previous bin (llama_v2_7b_chat_quantized_TokenGenerator_2_Quantized.bin).
For the other inputs (input[4~515]), the outputs (output[0~511]) of the previous bin (llama_v2_7b_chat_quantized_TokenGenerator_2_Quantized.bin) are converted to float, using the function (m_ioTensor.convertToFloat), which was implemented by Qualcomm. (using the offset=-128  scale=0.xxxxx which are provided bin file).
and the floats are converted to pytorch.tensor(float32) and the tensors are added to the past_key_values (which were saved from the previous PromptProcessor_1/2/3/4 or TokenGenerator_1/2/3/4), and the past_key_values are Sliced to remove oldest value. These past_key_values will be used in the next TokenGenerator cycle (TokenGenerator_1/2/3/4).
The past_key_values (0~2047) has the tensor shape [1, 1, 128, 1023] or [1, 1, 1023, 128], and it's data type is QNN_DATATYPE_UFIXED_POINT_8.
For the other inputs (input[4~515]), the past_key_values (which were saved from the previous PromptProcessor_1/2/3/4 or TokenGenerator_1/2/3/4) are converted to QNN_DATATYPE_UFIXED_POINT_8, using the the function (m_ioTensor.copyFromFloatToNative), which was implemented by Qualcomm. (using the offset=-128  scale=0.xxxxx which are provided bin file).

Best regards,

**Comment by bhushan23** [comment]
Hi @taeyeonlee we will be releasing Android app soon that uses Genie C++ APIs for e2e model execution.
Please refer to https://github.com/quic/ai-hub-models/tree/main/qai_hub_models/models/llama_v2_7b_chat_quantized/gen_ondevice_llama to run llama2 models on device with Genie using local executable.

If not using Genie, then you'll have to implement tokenizer, rope-embeddings into driver code of your App.
