### ISSUE TITLE
Has the AiHub's Whisper model been retrained?

### ISSUE THREAD

**Issue by zzy981019** [quic/ai-hub-models#90]
Hi, these are really great works! I would like to know if your Whisper model is based on OpenAi's Whisper model? And has it been retrained?
Thanks!

**Comment by gustavla** [comment]
The OpenAI Whisper model has not been re-trained. It is the original model from OpenAI.

**Comment by zzy981019** [comment]
> The OpenAI Whisper model has not been re-trained. It is the original model from OpenAI.

I get it, thank you!
