### ISSUE TITLE
Does not support XR2 GEN2 chip?

### ISSUE THREAD

**Issue by brisyramshere** [quic/ai-hub-models#92]

**Comment by mestrona-3** [comment]
Hi @brisyramshere, we do support the XR2 Gen2 chip on app.aihub.qualcomm.com. Check out the [getting started steps](https://aihub.qualcomm.com/get-started), which includes all the devices we currently support (by running qai-hub list-devices). 

We don't have XR2 Gen2 on aihub.qualcomm.com under our pre-optimized models yet, however you can modify the device in any of the export.py scripts to be the XR2Gen2. We recommend setting this manually as the device for the time being. Let us know via [Slack](https://aihub.qualcomm.com/community/slack) if you hit any issues.
