### ISSUE TITLE
[BUG] Mobile BYOM Issue: <insert issue here> OnePlus 9 Pro modelo LE2121

### ISSUE THREAD

**Issue by Alexanbezerra** [quic/ai-hub-models#93]
**Describe the issue**
Please provide details relating to the issue you're hitting, if it is related to performance, accuracy or other model issues with bringing your own model to Qualcomm AI Hub, to deploy to mobile devices.

**To Reproduce**
Please provide clear steps as to how the issue occurred. Either provide a job link or exact steps (i.e. go to xx model, scroll down and click on xx).

**Expected behavior**

**Stack trace**

**Host configuration:**
 - OS and version: [e.g. Linux, Windows, macOS]
 - QAI-Hub-Models version:
 - QAI-Hub client version:

**Additional context**

**Comment by Alexanbezerra** [comment]
O meu aparelho celular é um OnePlus 9 Pro modelo LE2121 com sistema Android

**Comment by mestrona-3** [comment]
Hi @Alexanbezerra , please provide more details as to the issue that you're facing. We provide over 100 pre-optimized models that work across Android devices depending on the runtime (tflite, QNN or ONNX) and device you're targeting. We also support bringing your own model to app.aihub.qualcomm.com in various source formats (PyTorch, ONNX, AIMET) and compiling it yourself, to then use the optimized asset on device. Check out the [getting started steps](https://aihub.qualcomm.com/get-started), which includes all the devices we currently support (by running qai-hub list-devices, we have the Xiaomi Redmi Note 10 5G (onePlus). You can deploy this asset on device by bundling it in your application.
