### ISSUE TITLE
[BUG] Mobile BYOM Issue: How to generate .tflite models form export?

### ISSUE THREAD

**Issue by XinyuGroceryStore** [quic/ai-hub-models#94]
**Describe the issue**
I want to get .tflite model. I have an app which can deploy tensorflow lite models, while it only accepts .tflite file. I followed the instructions [here](https://huggingface.co/qualcomm/Llama-v2-7B-Chat), and in the end it says the model can be .tflite exported. But I don't know how to get .tflite model files.

**To Reproduce**
I ran command below to learn the usages, but no options like "--target-runting tflite".
```
python -m qai_hub_models.models.llama_v2_7b_chat_quantized.export -h
``` 
Then I ran the command below, and only .bin models are downloaded.
```
python -m qai_hub_models.models.llama_v2_7b_chat_quantized.export --device "XR2 Gen 2 (Proxy)"
``` 

**Expected behavior**
I want to get LLM files of .tflite type.

**Host configuration:**
 - OS and version: Windows 10 (in virtual python env)
 - Browser:  chrome
 - QAI-Hub-Models version: latest of this issue posted

**Comment by Midi12** [comment]
@XinyuGroceryStore 

You can download the model using the Python API, below is minimal example.

The default target seems to be TFLITE models (notice no target passed in submit_compile_job).

```python
import qai_hub as hub
import torch
from torchvision.models import mobilenet_v2

torch_model = mobilenet_v2(pretrained=True)
torch_model.eval()

input_shape = (1, 3, 224, 224)
example_input = torch.rand(input_shape)
traced_torch_model = torch.jit.trace(torch_model, example_input)

compile_job = hub.submit_compile_job(
    model=traced_torch_model,
    device=hub.Device("QCS6490 (Proxy)"),
    input_specs=dict(image=input_shape),
)

target_model = compile_job.get_target_model()
target_model.download("mobilenet_v2.tflite")
```

**Comment by XinyuGroceryStore** [comment]
Thank you. But I want to use llama-2 model that was mentioned in Qualcomm AI Hub. Can you tell me the python api including llama-2 or llama-3 model?在 2024年8月27日，16:36，Midi12 ***@***.***> 写道：﻿
@XinyuGroceryStore
You can download the model using the Python API, below is minimal example.
The default target seems to be TFLITE models (notice no target passed in submit_compile_job).
import qai_hub as hub
import torch
from torchvision.models import mobilenet_v2

torch_model = mobilenet_v2(pretrained=True)
torch_model.eval()

input_shape = (1, 3, 224, 224)
example_input = torch.rand(input_shape)
traced_torch_model = torch.jit.trace(torch_model, example_input)

compile_job = hub.submit_compile_job(
    model=traced_torch_model,
    device=hub.Device("QCS6490 (Proxy)"),
    input_specs=dict(image=input_shape),
)

target_model = compile_job.get_target_model()
target_model.download("mobilenet_v2.tflite")

**Comment by mestrona-3** [comment]
Hi @XinyuGroceryStore , thank you for the question. Llama family of models are a bit different than others on AI Hub Models, as you've noticed. For these models, you need to run the export.py yourself to generate the model. 

For llama2 you need to fetch the weights from Meta. Follow ReadMe and steps here: https://github.com/quic/ai-hub-models/tree/main/qai_hub_models/models/llama_v2_7b_chat_quantized. 

Once you have followed the steps in the ReadMe when you export model from qai-hub-models, it upload .aimet model on AI Hub.
.aimet model has .onnx model in it

You can download source model from compile job to get .onnx model
https://github.com/quic/ai-hub-models/tree/main/qai_hub_models/models/llama_v2_7b_chat_quantized#export-for-on-device-deployment
