### ISSUE TITLE
ModuleNotFoundError: No module named 'libPyIrGraph'

### ISSUE THREAD

**Issue by Harsha0056** [quic/ai-hub-models#97]
**Describe the bug**
when trying to run 
 python gen_ondevice_llama.py --hub-model-id mrmdw7lwq,mjqyx81rm,m1q8748pm,m0q92582m,m9m551gym,m7qk5wy7q,m1m60802m,mwn0k9zzq --output-dir ./export --tokenizer-zip-path ./tokenizer.zip --target-gen snapdragon-gen2 --target-os windows
 
 On a docker machine with base image Ubuntu 22.04 and python 3.10  on HP Elitebook ultra laptop with processor Snapdragon(TM) X Elite - X1E78100 - Qualcomm(TM) Oryon(TM) CPU   3.42 GHz

**Error**
Using previously extracted model
Generating model lib for split-0 pp
./export/intermediate_data/input_data/data_pp_0.h5 export/intermediate_data/input_data/data_pp_0/_data
/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/bin/x86_64-linux-clang/qnn-onnx-converter --input_network ./export/intermediate_data/input_models/model_pp_0/Llama2_PromptProcessor_1_Quantized.aimet/Llama2_PromptProcessor_1_Quantized.onnx --output_path ./export/intermediate_data/cpp_models/Llama2_PromptProcessor_1_Quantized.cpp --no_simplification --quantization_overrides ./export/intermediate_data/input_models/model_pp_0/Llama2_PromptProcessor_1_Quantized.aimet/Llama2_PromptProcessor_1_Quantized.encodings --preserve_io layout input_ids attention_mask position_ids_cos position_ids_sin layers_7_add_out_0 past_key_0_out past_value_0_out past_key_1_out past_value_1_out past_key_2_out past_value_2_out past_key_3_out past_value_3_out past_key_4_out past_value_4_out past_key_5_out past_value_5_out past_key_6_out past_value_6_out past_key_7_out past_value_7_out --input_layout attention_mask NONTRIVIAL --input_layout position_ids_cos NONTRIVIAL --input_layout position_ids_sin NONTRIVIAL --input_list export/intermediate_data/input_data/data_pp_0/_data/input_list.txt --input_dim input_ids 1,1024 --input_dim attention_mask 1,1,1024,1024 --input_dim position_ids_cos 1,1,1024,64 --input_dim position_ids_sin 1,1,1024,64 --input_dtype input_ids int32 --input_dtype attention_mask float32 --input_dtype position_ids_cos float32 --input_dtype position_ids_sin float32 --bias_bitwidth 32 --weight_bw 8 --act_bitwidth 16
Traceback (most recent call last):
  File "/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/lib/python/qti/aisw/converters/common/__init__.py", line 85, in <module>
    from . import libPyIrGraph as ir_graph
ImportError: cannot import name 'libPyIrGraph' from partially initialized module 'qti.aisw.converters.common' (most likely due to a circular import) (/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/lib/python/qti/aisw/converters/common/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/bin/x86_64-linux-clang/qnn-onnx-converter", line 12, in <module>
    from qti.aisw.converters import onnx as onnx_frontend
  File "/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/lib/python/qti/aisw/converters/onnx/__init__.py", line 8, in <module>
    from .onnx_to_ir import OnnxConverterFrontend
  File "/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/lib/python/qti/aisw/converters/onnx/onnx_to_ir.py", line 14, in <module>
    from qti.aisw.converters.common.utils import code_to_message
  File "/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/lib/python/qti/aisw/converters/common/__init__.py", line 95, in <module>
    raise e
  File "/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/lib/python/qti/aisw/converters/common/__init__.py", line 53, in <module>
    import libPyIrGraph as ir_graph
ModuleNotFoundError: No module named 'libPyIrGraph'
Generating model lib...
/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/bin/x86_64-linux-clang/qnn-model-lib-generator -c ./export/intermediate_data/cpp_models/Llama2_PromptProcessor_1_Quantized.cpp -b ./export/intermediate_data/cpp_models/Llama2_PromptProcessor_1_Quantized.bin -t x86_64-linux-clang -o ./export/intermediate_data/model_libs -l Llama2_PromptProcessor_1_Quantized
2024-09-13 14:15:20,021 -    INFO - qnn-model-lib-generator: Model cpp file path  : export/intermediate_data/cpp_models/Llama2_PromptProcessor_1_Quantized.cpp
2024-09-13 14:15:20,021 -    INFO - qnn-model-lib-generator: Model bin file path  : export/intermediate_data/cpp_models/Llama2_PromptProcessor_1_Quantized.bin
2024-09-13 14:15:20,021 -    INFO - qnn-model-lib-generator: Library target       : [['x86_64-linux-clang']]
2024-09-13 14:15:20,022 -    INFO - qnn-model-lib-generator: Library name         : Llama2_PromptProcessor_1_Quantized
2024-09-13 14:15:20,022 -    INFO - qnn-model-lib-generator: Output directory     : export/intermediate_data/model_libs
Traceback (most recent call last):
  File "/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/bin/x86_64-linux-clang/qnn-model-lib-generator", line 495, in <module>
    main()
  File "/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/bin/x86_64-linux-clang/qnn-model-lib-generator", line 489, in main
    result = generator.build_targets(config)
  File "/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/bin/x86_64-linux-clang/qnn-model-lib-generator", line 393, in build_targets
    self._normalize_config(config)
  File "/opt/qualcomm_ai_engine_direct.2.25.0.240728.Linux-AnyCPU/bin/x86_64-linux-clang/qnn-model-lib-generator", line 361, in _normalize_config
    raise FileNotFoundError(f'Unable to find the model source file, invalid path: {config.model_cpp.absolute()}')
FileNotFoundError: Unable to find the model source file, invalid path: /opt/export/intermediate_data/cpp_models/Llama2_PromptProcessor_1_Quantized.cpp
Traceback (most recent call last):
  File "/opt/gen_ondevice_llama.py", line 67, in <module>
    main()
  File "/opt/gen_ondevice_llama.py", line 61, in main
    generate_shared_bins(
  File "/opt/utils.py", line 546, in generate_shared_bins
    generate_lib(
  File "/opt/utils.py", line 276, in generate_lib
    raise RuntimeError("The QNN graph compiler did not produce the output file")
RuntimeError: The QNN graph compiler did not produce the output file

**Host configuration:**
 - OS and version: Linux
 - Browser : terminal
 - QAI-Hub-Models version: qai-hub-models==0.13.0
 - QAI-Hub client version: qai-hub==0.15.1

**Additional context**
Device Specs

Processor: Snapdragon(TM) X Elite - X1E78100 - Qualcomm(TM) Oryon(TM) CPU   3.42 GHz  which has both GPU and NPU

**Comment by bhushan23** [comment]
Hi @Harsha0056 qnn python tools require python3.10 
see https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-2/setup.html?product=1601111740010412

Could you please try install python310 for qnn virtualenv?

**Comment by quic-rneti** [comment]
Please make sure you are using Ubuntu amd version instead of ubuntu arm64.

**Comment by quic-rneti** [comment]
Dear User - as suggested above, this is purely a QNN SDK setup issue. For any AI SDK issues, please post your questions at https://mysupport.qualcomm.com/supportforums/s/ (AI SDK & Tools) 

AI Hub slack, and AI Hub github are intended for supporting AI Hub issues, not AI SDK issues.

**Comment by quic-rneti** [comment]
Dear User - Since you are running on X-Elite laptop, you can use windows qnn sdk for all conversion, quantization, and execution. 

Also, when you are installing python on X-Elite, you need to select ARM64 variants. 

For any further assistance on QNN SDK setup or any AI SDK related issues, please post at https://mysupport.qualcomm.com/supportforums/s/ (AI SDK & Tools)

**Comment by Harsha0056** [comment]
when i ran into this error ,  i tried in Ubuntu 22.04 , Linux x 86 Machine , with python 3.10 env and i got the same  error 
![QNN](https://github.com/user-attachments/assets/86a66760-256c-4a80-93ef-12f486dc1871)

**Comment by YLlllllllllll** [comment]
I have the same issue. Although the environment and Python version conform to the instructions, it keeps saying 'circular import' no matter how I reset the environment.
![image](https://github.com/user-attachments/assets/c5fdd1af-0f6f-43eb-86c8-e1b7d80105df)

**Comment by bhushan23** [comment]
HI @YLlllllllllll root cause is missing `libpython3.10.so`

you can install these package with the following command
```
sudo apt-get install python3-dev 
```

circular dependency issue is coming from partially imported object which is result of this missing so

**Comment by bhushan23** [comment]
> when i ran into this error , i even tried in Ubuntu 22.04 , Linux x 86 Machine , with python 3.10 env [ As these specs were mentioned in the repo] and i faced the same issue ![QNN](https://private-user-images.githubusercontent.com/153726150/370654676-86a66760-256c-4a80-93ef-12f486dc1871.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDExMTQsIm5iZiI6MTcyNzgwMDgxNCwicGF0aCI6Ii8xNTM3MjYxNTAvMzcwNjU0Njc2LTg2YTY2NzYwLTI1NmMtNGE4MC05M2VmLTEyZjQ4NmRjMTg3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNjQwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODg3Nzc5ZTg0NjlmNTU4MzNiMzhkM2Y0ODI0MWJjOThkNGYxYTM2MDIzYjExODkxYWVlNzIxNDg1MjQzM2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.r-LaFYTvG3Xc2Q9HxZdK2SamStTCEH3PX8SxOhqkzIA)

Hi @Harsha0056, as you can see there's an error with `libc++` as a root cause for this partial import.

Coudl you please install clang / libc++? sometimes you have to ensure these libraries are discoverable by build tools

**Comment by Harsha0056** [comment]
worked , followed the docs for env setup. Thanks :)

**Comment by legendever** [comment]
@Harsha0056 ,hi , i meet the same error, could you tell me how to fix this error.i think i have followed the doc for env setup. thank you

**Comment by Harsha0056** [comment]
> @Harsha0056 ,hi , i meet the same error, could you tell me how to fix this error.i think i have followed the doc for env setup. thank you

i followed the docs  for env setup , with linux  OS and it worked for me

**Comment by legendever** [comment]
@Harsha0056 another question， now i use ubuntu 20.04. should i must update ubuntu22.04,

**Comment by Harsha0056** [comment]
> @Harsha0056 another question， now i use ubuntu 20.04. should i must update ubuntu22.04,

That is what they suggested ...so Yep
